### PR TITLE
updating some things to clean up for final review

### PR DESCRIPTION
**Pull request by djdanielsson**
making some changes for the final review

### CODE REVIEW

**Comment by djdanielsson** [comment]
not positive I changed everything in release workflow to make it work in this repo but should be close

**Comment by djdanielsson** [comment]
./sigh because the upstream and downstream of the collection dependencies being named differently is causing complications in the CI, I have asked the dev team how to fix it but idk it might not be simple which then would require this collection to maintain it's own set of tests and keeping updating it to match

**Comment by djdanielsson** [comment]
giving up on the devtools GitHub actions

**Comment by djdanielsson** [comment]
CI won't work due to GitHub limitations, idk how to fix it when this collection requires a downstream collection

**Comment by guidograzioli** [comment]
Do not worry about the failure, it is because a PR cannot read the github secrets (ie. the token). The changeset is otherwise good to me, but I'd had preferred to use our "own" changelog workflow to generate it using the github PR titles instead of having to use PR fragments. However, LGTM

**Review by guidograzioli — APPROVED** [review]

**Pull request merged**
